### PR TITLE
Adding Project Requirements to README (Squash commit)

### PR DESCRIPTION
**Pull request by syeel**
requirments     

1 - 2: @TEELIHONG
3 - 4: @goaykailing
5: @leejiawei95
6: @chinonn
7: @naimsaleh
8: @azman94

### CODE REVIEW

**Comment by leejiawei95** [comment]
Added requirement 5.

**Comment by chinonn** [comment]
Added requirement 6

**Comment by syeel** [comment]
Before you commit, please press the **'Preview'** button to check for text formatting

**Comment by TEELIHONG** [comment]
Added requirement 1 & 2

**Comment by goaykailing** [comment]
Added requirement 3 & 4

**Comment by syeel** [comment]
untitled

**Comment by azman94** [comment]
Added requirement 8

**Review by TEELIHONG — APPROVED** [review]

**Pull request merged**
