### PR TITLE
Adding Requirements to README

### PR DESCRIPTION
**Pull request by syeel**
capture2
***

1 - 2: @TEELIHONG 
3 - 4: @goaykailing 
5: @leejiawei95 
6: @chinonn 
7: @naimsaleh 
8: @azman94

### CODE REVIEW

**Comment by TEELIHONG** [comment]
Added requirement 1 & 2

**Comment by goaykailing** [comment]
Added requirement 3 & 4

**Comment by leejiawei95** [comment]
Added requirement 5.

**Comment by chinonn** [comment]
Added requirement 6.

**Pull request merged**
